services:
  webapp:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - /marmoset-client/node_modules
      - .:/marmoset-client
version: "3.7"
