apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-job-animals
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 1
      template:
        spec:
          containers:
            - image: arikama/marmoset-cron-job-animals
              name: cron-animals
          restartPolicy: OnFailure
  schedule: "* * ? * *"
